# Generated by Django 5.0.3 on 2024-06-17 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShareJourneysApp', '0006_remove_diadiemdungchan_khoangthoigian_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('companion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_route', to='ShareJourneysApp.travelcompanion')),
                ('id_noiDen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noiDen', to='ShareJourneysApp.diadiemdungchan')),
                ('id_noiDi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noiDi', to='ShareJourneysApp.diadiemdungchan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
