# Generated by Django 5.0.3 on 2024-06-27 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShareJourneysApp', '0007_user_router'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('id_Den', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Den', to='ShareJourneysApp.local')),
                ('id_Don', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noiDon', to='ShareJourneysApp.local')),
                ('id_User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userRoute', to='ShareJourneysApp.travelcompanion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='User_Router',
        ),
    ]
