# Generated by Django 5.0.3 on 2024-06-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShareJourneysApp', '0008_userroute_delete_user_router'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelcompanion',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
